baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
contact_form_action = "https://formspree.io/f/mblglvqa"